# Generated by Django 4.2.3 on 2023-08-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_book_emailid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Employee',
        ),
    ]
